name = "ContactImplicitMPC"
uuid = "842347fd-0767-4ff8-b652-76aad5eb0a37"
authors = ["simon-lc <simonlc@stanford.edu>", "thowell <thowell@stanford.edu>"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DirectTrajectoryOptimization = "a9f42406-efe7-414c-8b71-df971cc98041"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QDLDL = "bfc457fd-c171-5ab7-bd9e-d5dbfc242d63"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RoboDojo = "2859eb88-988f-4613-a49e-c643bedbc906"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.0"
Colors = "0.12"
CoordinateTransformations = "0.6"
FFMPEG = "0.4"
FileIO = "1.9"
ForwardDiff = "0.10"
GeometryBasics = "0.3"
IfElse = "0.1"
JLD2 = "0.4"
MeshCat = "0.14.1"
MeshCatMechanisms = "0.8"
MeshIO = "0.4"
Meshing = "0.5"
Parameters = "0.12"
Quaternions = "0.4"
RoboDojo = "0.1.3 - 0.1.3"
Rotations = "1.0.2 - 1.0.2"
Scratch = "1.0"
StaticArrays = "1.2"
Symbolics = "0.1.29 - 0.1.29"
julia = "1.6"
