[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
